apiVersion: v1
kind: ConfigMap
metadata:
  name: market-place-iam
data:
  application.properties: |-
    spring.zipkin.baseUrl=http://zipkin:9411/
    spring.data.mongodb.uri=mongodb://market-place-mongodb-0.market-place-mongodb,market-place-mongodb-1.market-place-mongodb,market-place-mongodb-2.market-place-mongodb/products-db?serverSelectionTimeoutMS=10000&connectTimeoutMS=20000
    ribbon.http.client.enabled= true
    hystrix.command.default.execution.timeout.enabled=false
    ribbon.ConnectTimeout=100000
    ribbon.ReadTimeout=100000
    spring.jackson.default-property-inclusion=NON_NULL
    spring.mvc.throw-exception-if-no-handler-found=TRUE